apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: backend
        
        image: "{{ .Values.backend.image }}:{{ required "backend.tag is required" .Values.backend.tag }}"
        # IMPORTANT: replace 922120356958 with YOUR account ID
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres"       # Kubernetes service name
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD
        - name: REDIS_HOST
          value: "redis"   

        resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20

        startupProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10


