apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend

spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      imagePullSecrets:
      - name: ecr-secret

      containers:
      - name: frontend

        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"

        ports:
        - containerPort: 8000

        resources:
          requests:
            cpu: 50m
            memory: 64Mi

          limits:
            cpu: 200m
            memory: 256Mi