apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres

        image: "{{ .Values.postgres.image }}:{{ .Values.postgres.tag }}"

        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_NAME

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD

        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"

          limits:
            cpu: "1"
            memory: "512Mi"

        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10

        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5

        startupProbe:
          tcpSocket:
            port: 5432
          failureThreshold: 30
          periodSeconds: 10

        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

        - name: init-script
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

      - name: init-script
        configMap:
          name: postgres-init-script