apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque

stringData:
  DB_NAME: {{ .Values.secret.dbName }}
  DB_USER: {{ .Values.secret.dbUser }}
  DB_PASSWORD: {{ .Values.secret.dbPassword }}