apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  imagePullSecrets:
      - name: ecr-secret
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 922120356958.dkr.ecr.ap-south-2.amazonaws.com/gpay-frontend:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
